spring:
  application:
    name: uniq-backend
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
  error:
    include-message: always
  tomcat:
    accesslog:
      enabled: true
      directory: logs
    basedir: tomcat
